server:
  port: 8761

spring:
  application:
    name: discovery-server
  # Désactive les bannières et les logs inutiles au démarrage
  main:
    banner-mode: "off"
    log-startup-info: false

eureka:
  instance:
    # Utiliser localhost en local évite les lenteurs de résolution DNS Docker/Windows
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    # On force le serveur à être prêt instantanément
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  # Désactive les vérifications cloud inutiles au démarrage
  health:
    defaults:
      enabled: false