spring.application.name=discovery-server
server.port=8761

# Empêche le serveur de s'enregistrer lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Désactive le mode survie pour supprimer les instances mortes rapidement (utile en dev)
eureka.server.enable-self-preservation=false

# --- CORRECTIONS POUR LA STABILITÉ ---

# Augmente le délai d'éviction à 30s ou 60s pour laisser respirer ton processeur
eureka.server.eviction-interval-timer-in-ms=30000

# Augmente le timeout de réponse pour éviter les "SocketTimeoutException"
eureka.server.peer-node-read-timeout-ms=5000

# Force l'utilisation de l'IP pour que tout le monde se comprenne
eureka.instance.prefer-ip-address=true
# Optionnel : donne un nom clair à l'instance
eureka.instance.instance-id=${spring.application.name}:${random.value}