spring.application.name=analyste-service
server.port=8080

# Database - Utilisation des variables définies dans le Docker Compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Eureka - Correction de l'URL pour Docker
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.compatibility-verifier.enabled=false

# Remplace localhost par le nom du service dans docker-compose
spring.rabbitmq.host=projectiq-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Uploads
projectiq.upload-dir=/app/uploads/projects
spring.servlet.multipart.max-file-size=15MB

spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# MinIO Configuration
minio.url=http://projectiq-minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin