analyste-service:
  build: ./analyste-service
  container_name: projectiq-analyste-service
  restart: on-failure
  env_file: [.env]
  environment:
    - JAVA_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx512m
    - SPRING_DATASOURCE_URL=jdbc:postgresql://projectiq-postgres:5432/projectiq_db
    - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
    - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
  depends_on:
    postgres: # Doit correspondre au nom du service défini plus haut
      condition: service_healthy
    discovery-server:
      condition: service_healthy
    rabbitmq: # Important pour un service qui fait de l'extraction
      condition: service_healthy
    volumes:
      - ./uploads:/app/uploads/projects
    networks:
      - projectiq-network