spring.application.name=project-service
server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://projectiq-postgres:5432/projectiq_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
spring.cloud.compatibility-verifier.enabled=false


spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# MinIO Configuration
minio.url=http://projectiq-minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin