server:
  port: 9091

spring:
  application:
    name: admin-service

  mail:
    host: mailpit
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
eureka:
  instance:
    # FORCE L'IP : Indispensable pour que la Gateway le trouve
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      eureka:
        client:
          service-url:
            defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}:
