server.port=9091
spring.application.name=admin-service

# --- BASE DE DONNÉES ---
# Utilisation du nom du service docker 'projectiq-postgres'
spring.datasource.url=jdbc:postgresql://projectiq-postgres:5432/projectiq_admin_db
spring.datasource.username=postgres
spring.datasource.password=projectiq_postgres

# --- JPA / HIBERNATE ---
# 'update' permet d'ajouter la colonne 'ressource' manquante automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.user=postgres
spring.flyway.password=projectiq_postgres
spring.flyway.baseline-on-migrate=true
# On active le repair pour ignorer les erreurs de checksum si tu modifies tes scripts SQL
spring.flyway.repair-on-migrate=true

# --- EUREKA (IMPORTANT POUR DOCKER) ---
# 'localhost' ne fonctionne pas dans un container, il faut le nom du service docker
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- RABBITMQ ---
spring.rabbitmq.host=projectiq-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- CONFIGURATION JWT ---
jwt.secret=CetteCleFaitExactement64CaracteresEtElleEstTresStablePourLePFE2026
jwt.access-token-expiration-minutes=60

# --- MAIL (MAILPIT - LOCAL) ---
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false